# Numpy Lecture

## Imports

In [1]:
import numpy as np

## Creating an array

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

## Referencing the values in an array

In [3]:
my_array = np.array([1, 2, 3, 4, 5])

### Just like an list, we can access the values of a basic array with integer indexing

In [4]:
my_list = [1, 2, 3, 4, 5]

In [5]:
my_list[0]

1

In [6]:
my_array[0]

1

## Lists of lists and array of arrays

### We have made a list of lists

In [7]:
list_of_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

### We access the elements in these lists by repeatedly using integer indexing

In [8]:
list_of_list[1][1]

5

### With arrays we can make an array of arrays, also known as a matrix or a multidimensional array

In [9]:
matrix = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

In [10]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Unlike list of lists, we can access the elements inside much quicker

In [11]:
matrix[1, 1]

5

### In a two dimensional array, the first indexing number is the row and the second is the column

```python
matrix[row, column]
```

### We can access multiple elements in an array using slicing, like we did with lists

In [12]:
my_list[1:]

[2, 3, 4, 5]

In [13]:
my_array[1:]

array([2, 3, 4, 5])

### But unlike list of lists, I can do this with the multidimensional array too

In [14]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matrix[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Indexing with a boolean sequence, also known as a boolean mask

In [16]:
my_array

array([1, 2, 3, 4, 5])

In [17]:
mask = [False, True, False, True, False]

my_array[mask]

array([2, 4])

## Vectorized Operations

### Adding 1 to every element of a list

### Fails to just say list + 1

In [18]:
my_list

[1, 2, 3, 4, 5]

In [20]:
my_list + 1

TypeError: can only concatenate list (not "int") to list

### Using a for loop

In [21]:
list_with_one_added = []

for n in my_list:
    list_with_one_added.append(n + 1)
    
list_with_one_added

[2, 3, 4, 5, 6]

### Using list comprehension

In [22]:
my_list

[1, 2, 3, 4, 5]

In [23]:
[n + 1 for n in my_list]

[2, 3, 4, 5, 6]

In [24]:
my_array

array([1, 2, 3, 4, 5])

In [25]:
my_array + 1

array([2, 3, 4, 5, 6])

In [26]:
my_array

array([1, 2, 3, 4, 5])

### It works with our other mathmatical operators too

In [27]:
my_array - 5

array([-4, -3, -2, -1,  0])

In [28]:
my_array * 10

array([10, 20, 30, 40, 50])

In [29]:
my_array / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [30]:
my_array // 2

array([0, 1, 1, 2, 2])

In [31]:
my_array % 2

array([1, 0, 1, 0, 1])

In [32]:
my_array ** 5

array([   1,   32,  243, 1024, 3125])

### We can even vectorize our comparison operators

In [33]:
my_array

array([1, 2, 3, 4, 5])

In [34]:
my_array > 2

array([False, False,  True,  True,  True])

### We can use this boolean array to get back values that return True

In [35]:
my_array[my_array > 2]

array([3, 4, 5])

### In depth dive of what is happening with the comparison

In [36]:
my_array

array([1, 2, 3, 4, 5])

In [37]:
my_array[my_array % 2 == 0]

array([2, 4])

In [38]:
my_array % 2

array([1, 0, 1, 0, 1])

In [39]:
my_array % 2 == 1

array([ True, False,  True, False,  True])

In [40]:
new_array = my_array[my_array % 2 == 1]
new_array

array([1, 3, 5])

In [41]:
new_array[new_array > 2]

array([3, 5])

## Array Creation

### `np.random.randn()`

In [42]:
np.random.randn(10)

array([-0.19616945,  0.49937034, -1.0245105 ,  1.85344504,  0.47015883,
       -0.278093  , -2.16063645, -1.59754321,  0.55406388,  0.17295644])

In [43]:
np.random.randn(2, 2)

array([[-0.34932983,  1.29123562],
       [-1.34693005, -0.24649177]])

###  `np.zeros()` & `np.ones()` & `np.full()`

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [45]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones(3)

array([1., 1., 1.])

In [47]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.full(3, 15)

array([15, 15, 15])

In [49]:
np.full((3, 3), 15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

### `np.arange()`

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

#### What about decimals?

In [53]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### `np.linspace()`

In [54]:
np.linspace(1, 4, 5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

## Array Methods

###  `array.mean()`

In [55]:
my_array

array([1, 2, 3, 4, 5])

In [56]:
my_array.mean()

3.0

###  `array.min()`

In [57]:
my_array.min()

1

###  `array.max()`

In [58]:
my_array.max()

5

###  `array.sum()`

In [59]:
my_array.sum()

15

###  `array.std()`

In [60]:
my_array.std()

1.4142135623730951

In [61]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
matrix.mean()

5.0

In [71]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
matrix * matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [73]:
np.dot(matrix, matrix)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [74]:
matrix * np.array([1,2,3])

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [82]:
np.dot(matrix, np.array([1,2,3]))

array([14, 32, 50])

In [83]:
my_array = np.array([1,2])

In [78]:
matrix.shape

(3, 3)

In [79]:
my_array.shape

(3,)

In [84]:
matrix * my_array

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 