# Numpy Exercises

<hr style="border:2px solid gray">

Use the following code for the questions below:

```a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])```

1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is <b>centering</b>. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7. Calculate the z-score for each data point. Recall that the z-score is given by:

     Z = (x − μ) / σ

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

<hr style="border:1px solid black">
<hr style="border:1px solid black">

In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

<b>#1. How many negative numbers are there?</b>
- <b>Answer</b>: 4

In [45]:
#let's see how many are negative, how many are positive
#True will indicate the number is greater than 0 (positive)
#False will indicate the number is less than 0 (negative)
a<0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [46]:
#now we can mask this list to return only positive numbers
a[a<0]

array([-2, -1, -6, -7])

In [47]:
#and get the shape (quantity)
a[a<0].shape[0] 

4

In [48]:
#another option
len(a[a<0])

4

<hr style="border:0.5px solid grey">

<b>#2. How many positive numbers are there?</b>
- <b>Answer</b>: 5

In [49]:
#if a is less than 0, we will get a true
a>0

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [50]:
#mask these responses to only get negatives
a[a>0]

array([ 4, 10, 12, 23,  3])

In [52]:
#now we can get a count
len(a[a>0])

5

In [53]:
#another option
a[a>0].shape[0]

5

<hr style="border:0.5px solid grey">

<b>#3. How many even positive numbers are there?</b>
- <b>Answer</b>: 3

In [11]:
#take a look at the original array
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [54]:
#let's get all the evens
even = a[a % 2 ==0]
even

array([ 4, 10, 12, -2,  0,  0,  0, -6])

In [14]:
#how many even numbers do we have in our original list
even.shape[0]

8

In [15]:
#now, let's get all the positive numbers from our evens list
even[even>0]

array([ 4, 10, 12])

In [16]:
#count on that to answer question
len(even[even>0])

3

In [56]:
#Jon Style!
how_many = a[(a>0) & (a%2==0)]
len(how_many)

3

<hr style="border:0.5px solid grey">

<b>#4. If you were to add 3 to each data point, how many positive numbers would there be?</b>
- <b>Answer</b>: 10

In [57]:
#add 3 to every number in the array
add_three = a+3

#take a look
add_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [18]:
#that leaves us with 12 numbers still
add_three.shape[0]

12

In [20]:
#now, how many positive numbers are there
len(a[(a+3)>0])

10

In [ ]:
#other way


<hr style="border:0.5px solid grey">

<b>#5. If you squared each number, what would the new mean and standard deviation be?</b>
- <b>Answers</b>:
    - Mean: 74
    - Standard Deviation: 144.02

In [21]:
#first, let's square our original array
a_squared = a ** 2

In [22]:
#take a look
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [23]:
#what is the mean of our new squared array
a_squared.mean()

74.0

In [24]:
#what is the stdev of our new squared array
a_squared.std()

144.0243035046516

In [60]:
#Annie Style!
np.mean(a**2), np.std(a**2)

(74.0, 144.0243035046516)

<hr style="border:0.5px solid grey">

<b>#6. A common statistical operation on a dataset is <b>centering</b>. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [25]:
#remember what 'a' looks like
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [32]:
#what is the actual mean of our original array
a.mean()

3.0

In [34]:
#assign variable to the array minus the mean of the array
centered_a = a - a.mean()

In [35]:
#take a look
centered_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [36]:
#double check that we are at 0 (centered)
centered_a.mean()

0.0

<hr style="border:0.5px solid grey">

<b>#7. Calculate the z-score for each data point. Recall that the z-score is given by:

     Z = (x − μ) / σ

In [61]:
#long way
z = (a - a.mean())/a.std()

In [42]:
#look at it
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [43]:
#or we can realize that 'a-a.mean' is the same as centered_a
z_scores = centered_a / a.std()

In [44]:
#take a look
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [64]:
#using an import
import scipy.stats as stats

In [65]:
#using import scipy to get the zscore
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

<hr style="border:0.5px solid grey">

<b>#8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.